#!/bin/bash

PASSWORD=`cat ./config2`
#echo $PASSWORD

TOKEN=`curl -X POST https://bsky.social/xrpc/com.atproto.server.createSession -H "Content-Type: application/json" -d '{
  "identifier": "faust-bot.bsky.social",
  "password": "'"$PASSWORD"'"
}' | sed 's|.*accessJwt":"||g' | sed 's|".*||g'`

#echo $TOKEN



DATE=`date -d "today" '+%Y-%m-%d'`

#echo $DATE

SEARCHSTRINGS="cat without a grin
brillig, and the slithy toves
O frabjous day
a poor sort of memory that only works backwards
no use going back to yesterday, because I was a different person then
The time has come, the Walrus said
Curiouser and curiouser, said Alice
It was the best butter
snark was a boojum
you are old, father william, the young man said
Alice’s Adventures In Wonderland
Alice's Adventures in Wonderland
lewis carroll bot
We’re all mad here
If you don’t know where you are going, any road will get you there
Begin at the beginning…and go on till you come to the end then stop
sometimes I’ve believed as many as six impossible things before breakfast
It’s a poor sort of memory that only works backward
jam tomorrow and jam yesterday but never jam today
Life what is it but a dream
What I tell you three times is true
"

printf %s "$SEARCHSTRINGS" | 
while IFS= read -r line; do


POSTS=$( curl -s -G "https://faust-bot.bsky.social/xrpc/app.bsky.feed.searchposts" \
    --data-urlencode "q=${line}" \
    --data-urlencode "since=${DATE}T00:00:01.123Z" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer $TOKEN"\
 | sed "s|uri|\n|g" \
| grep handle | awk -F [\"] '{print   $3 " "  $7 " "   $17 }'
)

if [[ "$POSTS" != "" ]]; then

printf %s "$POSTS
" | 
while IFS= read -r perams; do

THISPOSTER=`echo $perams |awk '{ print $3}'`

if [[ `echo $ALLPOSTERS | grep $THISPOSTER` == "" ]]; then
ALLPOSTERS=$ALLPOSTERS$THISPOSTER


URI=`echo $perams |awk '{ print $1}'`
CID=`echo $perams |awk '{ print $2}'`


echo "$URI $CID"
echo $THISPOSTER
echo $ALLPOSTER
echo "$line"

echo " 
module.exports = {
  myuri: '$URI',
  mycid: '$CID'
};
" > /home/larsen_online/faust-bot/uri-cid


/home/larsen_online/.nvm/versions/node/v18.20.2/bin/node /home/larsen_online/faust-bot/likeit.js
else
echo "SKIPPING $THISPOSTER"
fi
done

fi


done

