#!/bin/bash


TOKEN='eyJhbGciOiJFUzI1NksifQ.eyJzY29wZSI6ImNvbS5hdHByb3RvLmFjY2VzcyIsInN1YiI6ImRpZDpwbGM6MmxiNWtpZ3Y3b3loY3VjeXc2d3BveW9kIiwiaWF0IjoxNzE3NDg3MjcwLCJleHAiOjE3MTc0OTQ0NzAsImF1ZCI6ImRpZDp3ZWI6dmVycGEudXMtd2VzdC5ob3N0LmJza3kubmV0d29yayJ9.k9CW0EQV5XvKf9ZZGKPrXIA66oF6hPKCG80nLzrvn5O-lxQ-B2vBaix9r7ZdcN4L0xRVHTerbglp9wxI5QZOqg'

DATE=`date -d "today" '+%Y-%m-%d'`

#echo $DATE

SEARCHSTRINGS="Zwei Seelen wohnen, ach! in meiner Brust
Das also war des Pudels Kern
Verweile doch, du bist so schön
Grau ist alle Theorie, und grün des Lebens goldner Baum
Im Anfang war die Tat.
Wer immer strebend sich bemüht, den können wir erlösen
Das Ewig-Weibliche zieht uns hinan
Des Lebens Pulse schlagen früh und spät
Die Botschaft hör' ich wohl, allein mir fehlt der Glaube
Ein Teil von jener Kraft, die stets das Böse will und stets das Gute schafft
Ich bin der Geist, der stets verneint
steh' ich nun, ich armer Tor
Vom Eise befreit sind Strom und Bäche durch des Frühlings holden, belebenden Blick
Ich wünschte mir den allerderbsten Bock
Es war ein König in Thule
Fühlt man erst recht des Basses Grundgewalt
Es irrt der Mensch, solang er strebt
Der Worte sind genug gewechselt, lasst mich auch endlich Taten sehn
Hier bin ich Mensch, hier darf ich’s sein
Nach Golde drängt, am Golde hängt doch alles
Zwar weiß ich viel, doch möcht ich alles wissen
Heinrich! Mir graut’s vor dir.
Mein schönes Fräulein, darf ich wagen, Meinen Arm und Geleit Ihr anzutragen
"

printf %s "$SEARCHSTRINGS" | 
while IFS= read -r line; do


STRING=`echo $line | sed 's| |%20|g' | sed 's|ö|%C3%B6|g' | sed 's|ä|%C3%A4|g' | sed 's|ü|%C3%BC|g' | sed 's|ß|%C3%9F|g' | sed 's|\?|%3F|g' | \
sed "s|'|%27|g" | sed 's|\!|%21|g' | sed 's|,|%2C|g'`

#echo "$STRING"



POSTS=`curl -L -X GET "https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts?q=\"${STRING}\"&since=${DATE}T00:00:01.123Z" -H 'Accept: application/json' -H 'Authorization: Bearer $TOKEN' | sed "s|uri|\n|g" \
| grep handle | awk -F [\"] '{print   $3 " "  $7 " "   $17 }'`

#curl -L -X GET "https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts?q=\"${STRING}\"&since=${DATE}T23:59:59.123Z" -H 'Accept: application/json' -H 'Authorization: Bearer $TOKEN' | sed "s|uri|\n|g" \
#| grep handle | awk -F [\"] '{print   $3 " "  $7 " "   $17 }'




if [[ "$POSTS" != "" ]]; then

printf %s "$POSTS
" | 
while IFS= read -r perams; do

THISPOSTER=`echo $perams |awk '{ print $3}'`

if [[ `echo $ALLPOSTERS | grep $THISPOSTER` == "" ]]; then
ALLPOSTERS=$ALLPOSTERS$THISPOSTER


URI=`echo $perams |awk '{ print $1}'`
CID=`echo $perams |awk '{ print $2}'`


echo "$URI $CID"
echo $THISPOSTER
echo $ALLPOSTER
echo "$line"

echo " 
module.exports = {
  myuri: '$URI',
  mycid: '$CID'
};
" > /home/larsen_online/faust-bot/uri-cid


/home/larsen_online/.nvm/versions/node/v18.20.2/bin/node /home/larsen_online/faust-bot/likeit.js
else
echo "SKIPPING $THISPOSTER"
fi
done

fi


done
